# Generated by Django 6.1 on 2026-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'system'), (1, 'user'), (2, 'assistant')], verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('tokens', models.IntegerField(default=0, verbose_name='Token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI消息',
                'verbose_name_plural': 'AI消息',
                'db_table': 'ai_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='会话标题')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI会话',
                'verbose_name_plural': 'AI会话',
                'db_table': 'ai_chat_session',
                'ordering': ['-updated_at'],
            },
        ),
    ]
