# Generated by Django 6.1 on 2026-08-11 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='messaging.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_reads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '广播已读记录',
                'verbose_name_plural': '广播已读记录',
                'db_table': 'sys_message_read',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
