# Generated by Django 6.1 on 2026-08-18 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('priority', models.IntegerField(choices=[(1, '紧急'), (2, '高'), (3, '中'), (4, '低')], default=3, verbose_name='优先级')),
                ('difficulty', models.IntegerField(choices=[(1, '极高'), (2, '高'), (3, '中'), (4, '低')], default=3, verbose_name='难度等级')),
                ('benefit', models.DecimalField(blank=True, decimal_places=2, help_text='仅部分任务种类需要填写', max_digits=10, null=True, verbose_name='效益/积分')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='预计结束时间')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束时间')),
                ('progress', models.IntegerField(default=0, help_text='0-100 百分比', verbose_name='任务进度')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '审核通过'), ('in_progress', '进行中'), ('pending_verify', '待验证'), ('completed', '已完成'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='参与人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='TaskManagement.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'db_table': 'task_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='种类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='种类编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('has_benefit', models.BooleanField(default=False, help_text='该种类任务是否需要填写效益/积分', verbose_name='是否有效益')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '任务种类',
                'verbose_name_plural': '任务种类',
                'db_table': 'task_category',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='TaskManagement.taskcategory', verbose_name='任务种类'),
        ),
        migrations.CreateModel(
            name='TaskPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.DecimalField(decimal_places=2, default=0, help_text='基于难度的基础积分', max_digits=10, verbose_name='基础积分')),
                ('priority_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优先级加成')),
                ('time_bonus', models.DecimalField(decimal_places=2, default=0, help_text='按时/提前完成加分，延期扣分', max_digits=10, verbose_name='时效加成')),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, help_text='主管对任务完成质量的评分', max_digits=10, verbose_name='质量评分')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总积分')),
                ('comment', models.TextField(blank=True, verbose_name='评分说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_performances', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='TaskManagement.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '绩效积分',
                'verbose_name_plural': '绩效积分',
                'db_table': 'task_performance',
            },
        ),
        migrations.CreateModel(
            name='TaskProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='0-100 百分比', verbose_name='进度')),
                ('description', models.TextField(blank=True, verbose_name='进度描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='TaskManagement.task', verbose_name='关联任务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '进度记录',
                'verbose_name_plural': '进度记录',
                'db_table': 'task_progress_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_task_status_5e4c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_task_priorit_21ce1f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner'], name='task_task_owner_i_03f94c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='task_task_created_364f03_idx'),
        ),
    ]
