# Generated by Django 6.1 on 2026-08-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
